title = "Levi Crews"
baseURL = "https://lgcrews.netlify.app/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true          # enable KaTeX (https://katex.org/) globally
googleAnalytics = "G-931B69WEG0"  # add your tracking id

[params]
  author = "Levi Crews"
  description = "I am an IES Postdoctoral Fellow at Princeton University. My research focuses on macroeconomics, spatial economics, and international trade."
  favicon = "img/icon-uclabear.png"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Made with hugo-researcher by O. Roques."
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Courier"
    fontSize = "11pt"
    pageWidth = "750px"
    avatarSize = "200px"
    colorBlack = "#222222"
    colorRed = "#2774AE"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:lcrews@princeton.edu"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/LeviGCrews"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/levicrews"
  [[params.socialIcons]]
    icon = "ai ai-cv"
    title = "CV"
    url = "files/crews-cv.pdf"

[permalinks]
  "/" = "/:filename"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
