# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "cv"
  url = "/files/crews-cv.pdf"
  weight = 20

[[main]]
  name = "papers"
  url = "/papers"
  weight = 30

[[main]]
  name = "teaching"
  url = "/teaching"
  weight = 40

#[[main]]
#  name = "notes"
#  url = "/notes"
#  weight = 50